# Auto-report action script, 2 times a day

name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '30 1,10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        REPORT_DATA: ${{ secrets.Data }}
      run: |
        echo "$REPORT_DATA" > ./data.json
        python report.py data.json "$STUID" "$PASSWORD"
